# Generated by Django 5.0.6 on 2024-07-04 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tea_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('types', models.CharField(choices=[('BT', 'Black Tea'), ('GT', 'Green Tea'), ('HT', 'Herbal Tea'), ('OT', 'Oolong Tea'), ('PT', 'Pu-erh Tea'), ('WT', 'White Tea')], max_length=2)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
